/*
 * PROJECT:     ReactOS Applications Manager
 * LICENSE:     GPL-2.0-or-later (https://spdx.org/licenses/GPL-2.0-or-later)
 * PURPOSE:     Classes for working with available applications
 */

#include "defines.h"
#include <shlobj.h>
#include <shlwapi.h>
#include <setupapi.h>
#include <commctrl.h>
#include "resource.h"
#include "appinfo.h"
#include "configparser.h"
#include "misc.h"
#include "minizip/ioapi.h"
#include "minizip/iowin32.h"
#include "minizip/unzip.h"

extern "C" {
    #include "minizip/ioapi.c"
    #include "minizip/iowin32.c"
    #include "minizip/unzip.c"
}

#define UNINSTALL_SUBKEY L"Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall"
#define INFSEC_DEFINST L"U"
#define INFSEC_DELREG L"DelReg"
#define INFSEC_DELDIR L"DelDirs" THIS CANNOT BE USED UNTIL DelNodeW(directory, ADN_DEL_IF_EMPTY) is fixed!!
#define INFSEC_DELFILEREL L"DFR" // Relative to install directory
#define INFSEC_DELFILELNK L"DFL"
#define INFHACK_NOVALSUF L" ;" // The ini functions cannot write a line without "=", hide it behind a comment
#define INFHACK_NOVALVAL L""
#define INFHACK_DELFILESUF INFHACK_NOVALSUF
#define INFHACK_DELFILEVAL INFHACK_NOVALVAL
#define DB_PUBLISHER L"Publisher"
#define DB_VERSION L"Version"
#define DB_GENINSTSECTION L"Generate"
#define DB_GENINST_DELFILEREL L"DelFiles" // Delete files generated by the application
#define DB_GENINST_DELREG L"DelReg"
#define DB_GENINST_ICON L"Icon"


static UINT
ErrorFromHResult(HRESULT hr)
{
    if (HIWORD(hr) == HIWORD(HRESULT_FROM_WIN32(!0)))
        return LOWORD(hr);
    else
        return hr;
}

static BOOL
DeleteDirectoryTree(LPCWSTR Dir, HWND hwnd = NULL)
{
    CStringW from(Dir);
    UINT cch = from.GetLength();
    from.Append(L"00");
    LPWSTR p = from.GetBuffer();
    p[cch] = p[cch + 1] = L'\0'; // Double null-terminate
    UINT fof = FOF_NOCONFIRMATION | FOF_NOERRORUI | FOF_SILENT;
    SHFILEOPSTRUCT shfos = { hwnd, FO_DELETE, p, NULL, (FILEOP_FLAGS)fof };
    return SHFileOperationW(&shfos);
}

static UINT
CreateDirectoryTree(LPCWSTR Dir)
{
    UINT err = SHCreateDirectory(NULL, Dir);
    return err == ERROR_ALREADY_EXISTS ? 0 : err;
}

static BOOL
GetSpecialPath(UINT csidl, CStringW &Path, HWND hwnd = NULL)
{
    LPWSTR p = Path.GetBuffer(MAX_PATH);
    if (!SHGetSpecialFolderPathW(hwnd, p, csidl, TRUE))
        return FALSE;
    Path.ReleaseBuffer();
    return TRUE;
}

static int
ExtractFilesFromZip(LPCWSTR Archive, const CStringW &OutputDir,
                    EXTRACTCALLBACK Callback, void *Cookie, UINT DefCodepage)
{
    const UINT pkzefsutf8 = 1 << 11; // APPNOTE; APPENDIX D
    zlib_filefunc64_def zff;
    fill_win32_filefunc64W(&zff);
    unzFile hzf = unzOpen2_64(Archive, &zff);
    if (!hzf)
        return UNZ_BADZIPFILE;
    CStringA narrow;
    CStringW path, dir;
    int zerr = unzGoToFirstFile(hzf);
    for (; zerr == UNZ_OK; zerr = unzGoToNextFile(hzf))
    {
        unz_file_info64 fi;
        zerr = unzGetCurrentFileInfo64(hzf, &fi, NULL, 0, NULL, 0, NULL, 0);
        if (zerr != UNZ_OK)
            break;
        LPSTR file = narrow.GetBuffer(fi.size_filename);
        zerr = unzGetCurrentFileInfo64(hzf, &fi, file, narrow.GetAllocLength(), NULL, 0, NULL, 0);
        if (zerr != UNZ_OK)
            break;
        narrow.ReleaseBuffer(fi.size_filename);
        narrow.Replace('/', '\\');
        while (narrow[0] == '\\')
            narrow = narrow.Mid(1);
        UINT codepage = (fi.flag & pkzefsutf8) ? CP_UTF8 : DefCodepage;
        UINT cch = MultiByteToWideChar(codepage, 0, narrow, -1, NULL, 0);
        cch = MultiByteToWideChar(codepage, 0, narrow, -1, path.GetBuffer(cch - 1), cch);
        if (!cch)
            break;
        path.ReleaseBuffer(cch - 1);
        DWORD fileatt = FILE_ATTRIBUTE_NORMAL, err;
        BYTE attsys = HIBYTE(fi.version), dos = 0, ntfs = 10, vfat = 14;
        if ((attsys == dos || attsys == ntfs || attsys == vfat) && LOBYTE(fi.external_fa))
            fileatt = LOBYTE(fi.external_fa);

        if (!NotifyFileExtractCallback(path, fi.uncompressed_size, fileatt,
                                       Callback, Cookie))
            continue; // Skip file

        path = BuildPath(OutputDir, path);
        SplitFileAndDirectory(path, &dir);
        if (!dir.IsEmpty() && (err = CreateDirectoryTree(dir)))
        {
            zerr = UNZ_ERRNO;
            SetLastError(err);
            break;
        }

        if ((zerr = unzOpenCurrentFile(hzf)) != UNZ_OK)
            break;
        zerr = UNZ_ERRNO;
        HANDLE hFile = CreateFileW(path, GENERIC_READ | GENERIC_WRITE,
                                   FILE_SHARE_READ | FILE_SHARE_DELETE,
                                   NULL, CREATE_ALWAYS, fileatt, NULL);
        if (hFile != INVALID_HANDLE_VALUE)
        {
            for (zerr = UNZ_OK; zerr == UNZ_OK;)
            {
                DWORD len = 1024 * 4, cb;
                LPSTR buf = narrow.GetBuffer(len);
                len = zerr = unzReadCurrentFile(hzf, buf, len);
                if (zerr <= 0)
                    break;
                zerr = WriteFile(hFile, buf, len, &cb, NULL) && cb == len ? UNZ_OK : UNZ_ERRNO;
            }
            CloseHandle(hFile);
        }
        unzCloseCurrentFile(hzf);
    }
    unzClose(hzf);
    return zerr == UNZ_END_OF_LIST_OF_FILE ? UNZ_OK : zerr;
}

static UINT
ExtractZip(LPCWSTR Archive, const CStringW &OutputDir,
           EXTRACTCALLBACK Callback, void *Cookie, UINT DefCodepage)
{
    int zerr = ExtractFilesFromZip(Archive, OutputDir, Callback, Cookie, DefCodepage);
    return zerr == UNZ_ERRNO ? GetLastError() : zerr ? ERROR_INTERNAL_ERROR : 0;
}

static UINT
ExtractCab(LPCWSTR Archive, const CStringW &OutputDir,
           EXTRACTCALLBACK Callback, void *Cookie)
{
    if (ExtractFilesFromCab(Archive, OutputDir, Callback, Cookie))
        return ERROR_SUCCESS;
    UINT err = GetLastError();
    return err ? err : ERROR_INTERNAL_ERROR;
}

enum { IM_PROGRESS = WM_APP, IM_END };

static struct InstallInfo
{
    CConfigParser &Parser;
    LPCWSTR AppName, ArchivePath, InstallDir, ShortcutFile;
    CStringW UninstFile, MainApp;
    UINT InstallDirLen, Error, Count;
    BOOL PerUser, Silent;
    HWND hDlg;

    inline HWND GetGuiOwner() const { return Silent ? NULL : hDlg; }
} *g_pInfo;

static UINT
ErrorBoxAndDie(UINT Error = GetLastError())
{
    if (!Error)
        Error = ERROR_INTERNAL_ERROR;
    WCHAR buf[400];
    UINT fmf = FORMAT_MESSAGE_IGNORE_INSERTS | FORMAT_MESSAGE_FROM_SYSTEM;
    FormatMessageW(fmf, NULL, Error, 0, buf, _countof(buf), NULL);
    MessageBoxW(g_pInfo->GetGuiOwner(), buf, 0, MB_ICONSTOP);
    PostMessage(g_pInfo->hDlg, IM_END, 0, 0);
    g_pInfo->Error = Error;
    return Error;
}

static LPCWSTR
GetCommonString(LPCWSTR Name, CStringW &Output, LPCWSTR Default = L"")
{
    BOOL found = g_pInfo->Parser.GetString(Name, Output);
    return (found && !Output.IsEmpty() ? Output : Output = Default).GetString();
}

static LPCWSTR
GetGenerateString(LPCWSTR Name, CStringW &Output, LPCWSTR Default = L"")
{
    UINT r = g_pInfo->Parser.GetSectionString(DB_GENINSTSECTION, Name, Output);
    return (r ? Output : Output = Default).GetString();
}

static UINT
GetRegWow()
{
    return (sizeof(void*) > 4 || IsSystem64Bit()) ? KEY_WOW64_32KEY : 0;
}

static BOOL
WriteReg(LPCWSTR Key, LPCWSTR Name, LPCWSTR Data, UINT Type = REG_SZ)
{
    HKEY hKey = g_pInfo->PerUser ? HKEY_CURRENT_USER : HKEY_LOCAL_MACHINE;
    UINT e = RegCreateKeyEx(hKey, Key, 0, NULL, 0, KEY_WRITE | GetRegWow(), NULL, &hKey, NULL);
    if (!e)
    {
        e = RegSetValueExW(hKey, Name, 0, Type, (BYTE *)Data, (lstrlenW(Data) + 1) * sizeof(WCHAR));
        RegCloseKey(hKey);
    }
    if (e)
        ErrorBoxAndDie(e);
    return !e;
}

static BOOL
WriteUnInf(LPCWSTR Section, LPCWSTR Name, LPCWSTR Data)
{
    BOOL result = WritePrivateProfileStringW(Section, Name, Data, g_pInfo->UninstFile);
    if (!result)
        ErrorBoxAndDie();
    return result;
}

static BOOL
AddUnDestinationFile(const CStringW &FullPath)
{
    return WriteUnInf(INFSEC_DELFILEREL, FullPath.Mid(g_pInfo->InstallDirLen) +
                      L",,,1" INFHACK_DELFILESUF, INFHACK_DELFILEVAL);
}

static HRESULT
GetCustomIconPath(CStringW &Path)
{
    if (*GetGenerateString(DB_GENINST_ICON, Path))
    {
        Path = BuildPath(g_pInfo->InstallDir, Path);

        int idx = PathParseIconLocation(Path.GetBuffer());
        Path.ReleaseBuffer();
        HICON hIco = NULL;
        if (ExtractIconExW(Path, idx, &hIco, NULL, 1))
            DestroyIcon(hIco);
        if (idx)
            Path.AppendFormat(L",%d", idx);
        return !hIco;
    }
    return E_FAIL;
}

static BOOL
CreateShortcut(const CStringW &Target)
{
    UINT csidl = g_pInfo->PerUser ? CSIDL_PROGRAMS : CSIDL_COMMON_PROGRAMS;
    CStringW path, dir, tmp, rel = g_pInfo->ShortcutFile;
    if (!GetSpecialPath(csidl, path))
        return TRUE; // Pretend everything is OK

    rel.Replace('/', '\\');
    path = BuildPath(path, rel.GetString());
    UINT SHPPFW = SHPPFW_DIRCREATE | SHPPFW_IGNOREFILENAME;
    HRESULT hr = SHPathPrepareForWriteW(g_pInfo->GetGuiOwner(), NULL, path, SHPPFW);
    if ((g_pInfo->Error = ErrorFromHResult(hr)) != 0)
        return !ErrorBoxAndDie(g_pInfo->Error);

    IShellLinkW *pSL;
    hr = CoCreateInstance(CLSID_ShellLink, NULL, CLSCTX_ALL, IID_IShellLinkW, (void**)&pSL);
    if (SUCCEEDED(hr))
    {
        if (SUCCEEDED(hr = pSL->SetPath(Target)))
        {
            if (SUCCEEDED(GetCustomIconPath(tmp)))
            {
                LPWSTR p = tmp.GetBuffer();
                int idx = PathParseIconLocation(p);
                pSL->SetIconLocation(p, idx);
            }
            IPersistFile *pPF;
            if (SUCCEEDED(hr = pSL->QueryInterface(IID_IPersistFile, (void**)&pPF)))
            {
                hr = pPF->Save(path, FALSE);
                pPF->Release();
            }
        }
        pSL->Release();
    }
    if (SUCCEEDED(hr))
    {
        tmp.Format(L"%u", 0x4000 + csidl);
        WriteUnInf(L"DestinationDirs", INFSEC_DELFILELNK, tmp);
        WriteUnInf(INFSEC_DELFILELNK, rel + INFHACK_DELFILESUF, INFHACK_DELFILEVAL);
        SplitFileAndDirectory(rel, &dir);
        tmp.Format(L"%%%u%%\\%s", 0x4000 + csidl, dir.GetString());
        WriteUnInf(INFSEC_DELDIR, tmp + INFHACK_DELFILESUF, INFHACK_DELFILEVAL);
    }
    else
    {
        ErrorBoxAndDie(ErrorFromHResult(hr));
    }
    return !g_pInfo->Error;
}

static BOOL
InstallFiles(const CStringW &SourceDir, const CStringW &FileSpec,
             const CStringW &DestinationDir)
{
    CStringW from = BuildPath(SourceDir, FileSpec), to, tmp;
    BOOL failed = FALSE, dots;
    WIN32_FIND_DATAW wfd;
    HANDLE hFind = FindFirstFileW(from, &wfd);
    if (hFind == INVALID_HANDLE_VALUE)
        return !ErrorBoxAndDie();

    for (;;)
    {
        from = BuildPath(SourceDir, wfd.cFileName);
        to = BuildPath(DestinationDir, wfd.cFileName);
        LPWSTR p = wfd.cFileName;
        if (wfd.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY)
        {
            dots = (p[0] == '.' && !p[1]) || (p[0] == '.' && p[1] == '.' && !p[2]);
            if (!dots)
            {
                g_pInfo->Error = CreateDirectoryTree(to);
                if (g_pInfo->Error)
                {
                    failed = ErrorBoxAndDie(g_pInfo->Error);
                }
                else
                {
                    tmp = BuildPath(L"%1%", to.Mid(g_pInfo->InstallDirLen));
                    failed = !WriteUnInf(INFSEC_DELDIR, tmp + INFHACK_DELFILESUF, INFHACK_DELFILEVAL);
                }

                if (!failed)
                {
                    failed = !InstallFiles(from, FileSpec, to);
                }
            }
        }
        else
        {
            failed = !MoveFileEx(from, to, MOVEFILE_COPY_ALLOWED | MOVEFILE_REPLACE_EXISTING);
            if (failed)
            {
                ErrorBoxAndDie();
            }
            else if (g_pInfo->UninstFile.IsEmpty())
            {
                g_pInfo->MainApp = to;
                // Base the INF filename on the main application executable
                p = PathFindExtension(wfd.cFileName);
                g_pInfo->UninstFile = BuildPath(to.Left(g_pInfo->InstallDirLen),
                                  CStringW(wfd.cFileName).Mid(0, p - wfd.cFileName) + L"_Un.inf");
                HANDLE hFile = CreateFileW(g_pInfo->UninstFile, GENERIC_WRITE, FILE_SHARE_READ | FILE_SHARE_DELETE, 
                                           NULL, OPEN_ALWAYS, 0, NULL);
                if (hFile != INVALID_HANDLE_VALUE)
                {
                    BYTE bom[2] = { 0xFF, 0xFE };
                    DWORD cb;
                    WriteFile(hFile, bom, sizeof(bom), &cb, NULL);
                    CloseHandle(hFile);
                }
            }
            if (!failed)
            {
                failed = !AddUnDestinationFile(to);
            }
            SendMessage(g_pInfo->hDlg, IM_PROGRESS, 0, 0);
        }

        if (failed || !FindNextFileW(hFind, &wfd))
            break;
    }
    FindClose(hFind);
    return !failed;
}

static BOOL CALLBACK
ExtractCallback(const EXTRACTCALLBACKINFO &, void *Cookie)
{
    InstallInfo &Info = *(InstallInfo *) Cookie;
    Info.Count += 1;
    return TRUE;
}

static DWORD CALLBACK
ExtractAndInstallThread(LPVOID Parameter)
{
    const BOOL PerUserModeDefault = FALSE;
    InstallInfo &Info = *(InstallInfo *) Parameter;
    LPCWSTR AppName = Info.AppName, Archive = Info.ArchivePath, None = L"!";
    CStringW installdir, tempdir, files, shortcut, tmp;
    Info.Count += 1; // Cleanup

    if (!*GetGenerateString(L"Files", files))
        return ErrorBoxAndDie(ERROR_BAD_FORMAT);

    GetCommonString(L"For", tmp);
    if (!tmp.CompareNoCase(L"User"))
        Info.PerUser = TRUE;
    else if (!tmp.CompareNoCase(L"Machine"))
        Info.PerUser = FALSE;
    else
        Info.PerUser = PerUserModeDefault;

    // TODO: FOLDERID_UserProgramFiles
    if (!GetSpecialPath(Info.PerUser ? CSIDL_LOCAL_APPDATA : CSIDL_PROGRAM_FILES,
                        installdir, Info.GetGuiOwner()))
        return ErrorBoxAndDie();
    if (Info.PerUser)
        installdir = BuildPath(installdir, L"Programs");

    GetGenerateString(L"Dir", tmp);
    if (tmp.Compare(None))
        installdir = BuildPath(installdir, tmp.IsEmpty() ? AppName : tmp.GetString());
    Info.InstallDir = installdir.GetString();
    Info.InstallDirLen = installdir.GetLength() + 1;
    HRESULT hr = SHPathPrepareForWriteW(Info.GetGuiOwner(), NULL, installdir, SHPPFW_DIRCREATE);
    if ((Info.Error = ErrorFromHResult(hr)) != 0)
        return ErrorBoxAndDie(Info.Error);

    tempdir.Format(L"%s\\~RAM%u.tmp", installdir.GetString(), GetCurrentProcessId());
    Info.Error = CreateDirectoryTree(tempdir.GetString());
    if (Info.Error)
        return ErrorBoxAndDie(Info.Error);

    if (!*GetGenerateString(L"Lnk", shortcut))
        shortcut.Format(L"%s.lnk", AppName);
    Info.ShortcutFile = shortcut.Compare(None) ? shortcut.GetString() : NULL;

    BOOL isCab = SplitFileAndDirectory(Archive).Right(4).CompareNoCase(L".cab") == 0;
    INT codepage = 0;
    Info.Parser.GetInt(L"ArchiveCodepage", codepage);
    Info.Error = isCab ? ExtractCab(Archive, tempdir, ExtractCallback, &Info)
                       : ExtractZip(Archive, tempdir, ExtractCallback, &Info, codepage);
    if (!Info.Error)
    {
        Info.Count += 1; // Uninstaller
        SendMessage(Info.hDlg, IM_PROGRESS, (INT_PTR)-1, 0);

        CStringW item;
        int pos;
        for (pos = 1; pos > 0 && !Info.Error;)
        {
            pos = files.Find(L'|');
            item = pos <= 0 ? files : files.Left(pos);
            files = files.Mid(pos + 1);
            InstallFiles(tempdir, item, installdir);
        }

        if (!Info.UninstFile.IsEmpty())
        {
            CStringW uninstkey = UNINSTALL_SUBKEY;
            uninstkey.AppendFormat(L"\\%s%s", AppName, GENERATE_ARPSUFFIX);
            LPCWSTR infhk = Info.PerUser ? L"HKCU" : L"HKLM";
            UINT infwowregsam = (GetRegWow() & KEY_WOW64_32KEY) ? FLG_DELREG_32BITKEY : 0;

            tmp.Format(L"%s,\"%s\",,%d" INFHACK_NOVALSUF, infhk, uninstkey.GetString(), infwowregsam); // Note: ROS does not support FLG_DELREG_KEYONLY_COMMON.
            WriteUnInf(INFSEC_DELREG, tmp, INFHACK_NOVALVAL);
            if (*GetGenerateString(DB_GENINST_DELREG, tmp))
            {
                CStringW rp;
                for (pos = 1; pos > 0;)
                {
                    pos = tmp.Find(L'|');
                    item = pos <= 0 ? tmp : tmp.Left(pos);
                    tmp = tmp.Mid(pos + 1);
                    UINT wowsam = 0, ofs = 6;
                    rp = item.Left(ofs);
                    if (!rp.CompareNoCase(L"HKLM32"))
                        wowsam |= FLG_DELREG_32BITKEY;
                    else if (!rp.CompareNoCase(L"HKLM64"))
                        wowsam |= 0; // What can we do? ROS does not support FLG_ADDREG_DELVAL so we can't delete with AddReg either.
                    else
                        rp = item.Left(ofs = 4);
                    rp.Format(L"%s,\"%s\",,%d" INFHACK_NOVALSUF, rp.GetString(), item.Mid(++ofs).GetString(), wowsam);
                    WriteUnInf(INFSEC_DELREG, rp, INFHACK_NOVALVAL);
                }
            }

            WriteUnInf(L"Strings", L"N", AppName);
            WriteUnInf(L"SourceDisksNames", L"1", L"%N%");
            WriteUnInf(L"Version", L"Signature", L"$CHICAGO$");
            WriteUnInf(L"Version", L"AdvancedINF", L"2.5,\"Advanced Error\"");
            WriteUnInf(L"DestinationDirs", INFSEC_DELFILEREL, L"1");
            WriteUnInf(INFSEC_DEFINST, L"DelFiles", INFSEC_DELFILEREL L"," INFSEC_DELFILELNK);
            WriteUnInf(INFSEC_DEFINST, L"DelDirs", INFSEC_DELDIR);
            WriteUnInf(INFSEC_DEFINST, L"DelReg", INFSEC_DELREG);
            WriteUnInf(INFSEC_DEFINST, L"Cleanup", L"1");
            WriteUnInf(INFSEC_DEFINST, L"CheckAdminRights", Info.PerUser ? L"0" : L"1");

            WriteUnInf(INFSEC_DELDIR, L"%1%\\." INFHACK_DELFILESUF, INFHACK_DELFILEVAL);
            WriteUnInf(INFSEC_DEFINST, L"RunPostSetupCommands", L"PSC"); // ROS does not support the ":3" suffix?
            // Try extra hard to delete the empty install directory
            LPCWSTR rmdirselfcmd = L"\"\"\"%11%\\cmd.exe\"\" /D/C cd /D \"\"%11%\"\"&start \"\"\"\" /MIN cmd.exe /D/C ping -n 1 localhost^&rd \"\"%1%\"\"\"" INFHACK_NOVALSUF;
            WriteUnInf(L"PSC", rmdirselfcmd, INFHACK_NOVALVAL);

            if (*GetGenerateString(DB_GENINST_DELFILEREL, tmp))
            {
                for (pos = 1; pos > 0;)
                {
                    pos = tmp.Find(L'|');
                    item = pos <= 0 ? tmp : tmp.Left(pos);
                    tmp = tmp.Mid(pos + 1);
                    AddUnDestinationFile(installdir + L"\\" + item);
                }
            }
            AddUnDestinationFile(Info.UninstFile);

#if DBG
            WriteUnInf(L"DEBUG", L"installdir", installdir);
            WriteUnInf(L"DEBUG", L"shortcut", shortcut);
            tmp.Format(L"sys64=%d wowregsam=%#x", IsSystem64Bit(), GetRegWow());
            WriteUnInf(L"DEBUG", L"INFO", tmp);
#endif

            WriteReg(uninstkey, L"DisplayName", AppName);
            tmp.Format(L"\"%%WINDIR%%\\system32\\RunDLL32.exe\" advpack.dll,LaunchINFSection \"%s\",%s,,2",
                       Info.UninstFile.GetString(), INFSEC_DEFINST);
            WriteReg(uninstkey, L"UninstallString", tmp, REG_EXPAND_SZ);
            tmp = tmp.Mid(0, tmp.GetLength() - 1) + L"3";
            WriteReg(uninstkey, L"QuietUninstallString", tmp, REG_EXPAND_SZ);

            if (GetCustomIconPath(tmp) != S_OK)
                tmp = Info.MainApp;
            WriteReg(uninstkey, L"DisplayIcon", tmp);

            if (*GetCommonString(DB_VERSION, tmp))
                WriteReg(uninstkey, L"DisplayVersion", tmp);

            WriteReg(uninstkey, L"InstallLocation", Info.InstallDir);
            SYSTEMTIME st;
            GetSystemTime(&st);
            tmp.Format(L"%.4u%.2u%.2u", st.wYear, st.wMonth, st.wDay);
            WriteReg(uninstkey, L"InstallDate", tmp);
#ifdef DBPUBLISHER
            if (*GetCommonString(DB_PUBLISHER, tmp))
                WriteReg(uninstkey, L"Publisher", tmp);
#endif
            SendMessage(Info.hDlg, IM_PROGRESS, 0, 0); // Uninstaller
        }
        if (!Info.Error && Info.ShortcutFile)
        {
            CreateShortcut(Info.MainApp);
        }
    }

    DeleteDirectoryTree(tempdir.GetString());
    SendMessage(Info.hDlg, IM_PROGRESS, 0, 0); // Cleanup
    return (UINT) SendMessage(Info.hDlg, IM_END, 0, 0);
}

static INT_PTR CALLBACK
InstallerUIDlgProc(HWND hDlg, UINT uMsg, WPARAM wParam, LPARAM lParam)
{
    HWND hPB = GetDlgItem(hDlg, 1);
    switch(uMsg)
    {
        case IM_PROGRESS:
        {
            SendMessageW(hPB, PBM_DELTAPOS, 1, 0);
            if ((INT_PTR)wParam == (INT_PTR)-1)
            {
                SetWindowLongPtr(hPB, GWL_STYLE, WS_CHILD | WS_VISIBLE);
                SendMessageW(hPB, PBM_SETMARQUEE, FALSE, 0);
                SendMessageW(hPB, PBM_SETRANGE32, 0, g_pInfo->Count);
                SendMessageW(hPB, PBM_SETPOS, 0, 0);
            }
            break;
        }
        case IM_END:
            DestroyWindow(hDlg);
            break;
        case WM_INITDIALOG:
        {
            g_pInfo = (InstallInfo *)lParam;
            g_pInfo->hDlg = hDlg;
            HICON hIco = LoadIconW(hInst, MAKEINTRESOURCEW(IDI_MAIN));
            SendMessageW(hDlg, WM_SETICON, ICON_BIG, (LPARAM)hIco);
            SendMessageW(hDlg, WM_SETTEXT, 0, (LPARAM)g_pInfo->AppName);
            SendMessageW(hPB, PBM_SETMARQUEE, TRUE, 0);
            if (!SHCreateThread(ExtractAndInstallThread, g_pInfo, CTF_COINIT, NULL))
            {
                ErrorBoxAndDie();
            }
            SetThreadPriority(GetCurrentThread(), THREAD_PRIORITY_ABOVE_NORMAL);
            break;
        }
        case WM_CLOSE:
            return TRUE;
        case WM_DESTROY:
            PostMessage(NULL, WM_QUIT, 0, 0);
            break;
    }
    return FALSE;
}

BOOL
ExtractAndRunGeneratedInstaller(const CAvailableApplicationInfo &AppInfo, LPCWSTR Archive)
{
    CConfigParser &Parser = *AppInfo.GetConfigParserInstance();
    LPCWSTR AppName = AppInfo.szDisplayName.GetString();
    InstallInfo Info = { Parser, AppName, Archive };
    g_pInfo = &Info;

    enum { DLGW = 150, DLGH = 20, PAD = 4, PADx2 = PAD * 2, CHILDCOUNT = 1 };
    const UINT DlgStyle = WS_CAPTION | DS_MODALFRAME | DS_NOFAILCREATE | DS_CENTER;
    static const WORD DlgTmpl[] =
    {
        LOWORD(DlgStyle), HIWORD(DlgStyle), 0, 0, CHILDCOUNT, 0, 0, DLGW, DLGH, 0, 0, 0,
        PBS_MARQUEE, HIWORD(WS_CHILD | WS_VISIBLE), 0, 0, PAD, PAD, DLGW - PADx2, DLGH - PADx2, 1,
        'm', 's', 'c', 't', 'l', 's', '_', 'p', 'r', 'o', 'g', 'r', 'e', 's', 's', '3', '2', 0, 0,
    };
    HWND hWnd = CreateDialogIndirectParamW(NULL, (LPCDLGTEMPLATE)DlgTmpl, NULL, 
                                           InstallerUIDlgProc, (LPARAM)&Info);
    if (!hWnd)
    {
        ErrorBoxAndDie();
        return FALSE;
    }
    else if (!Info.Silent)
    {
        ShowWindow(hWnd, SW_SHOW);
    }

    MSG Msg;
    while (GetMessageW(&Msg, NULL, 0, 0))
    {
        TranslateMessage(&Msg);
        DispatchMessageW(&Msg);
    }
    return !Info.Error;
}
